export const drugs = [
  {
    name: 'Acetaminophen',
    drugGroup: 'NSAIDs',
    dosage: '500 mg',
    description: 'แก้ปวด ลดไข้',
    img: 'https://m.media-amazon.com/images/I/61LoOoJA8JL.jpg',
  },
  {
    name: 'Ibuprofen',
    drugGroup: 'NSAIDs',
    dosage: '200 mg',
    description: 'แก้ปวด ลดอักเสบ',
    img: 'https://static.wixstatic.com/media/nsplsh_724a56666c677161737234~mv2_d_4952_3888_s_4_2.jpg/v1/fill/w_1000,h_785,al_c,q_85,usm_0.66_1.00_0.01/nsplsh_724a56666c677161737234~mv2_d_4952_3888_s_4_2.jpg',
  },
  {
    name: 'Amoxicillin',
    drugGroup: 'antibiotic',
    dosage: '250 mg',
    description: 'ใช้สำหรับการต่อต้านเชื้อโรค',
    img: 'https://res.cloudinary.com/dk0z4ums3/image/upload/v1637737073/attached_image_th/antibioticpillgreenandbluecolourcapsules.jpg',
  },
  {
    name: 'Loratadine',
    drugGroup: 'antihistamine',
    dosage: '10 mg',
    description: 'ใช้สำหรับแก้อาการแพ้',
    img: 'https://hargravesotc.com/cdn/shop/products/Major_Loratadine_1200x1200.jpg?v=1625788303',
  },
  {
    name: 'Aspirin',
    drugGroup: 'NSAID',
    dosage: '325 mg',
    description: 'ลดอักเสบ ลดไข้',
    img: 'https://m.media-amazon.com/images/I/71-g7kjSLmL.jpg',
  },
  {
    name: 'Furosemide',
    drugGroup: 'diuretic',
    dosage: '40 mg',
    description: 'ใช้สำหรับลดอาการบวมน้ำ',
    img: 'https://vinmec-prod.s3.amazonaws.com/images/20210329_142410_064162_Furosemide-20mg2ml.max-1800x1800.jpg',
  },
  {
    name: 'Omeprazole',
    drugGroup: 'proton pump inhibitor',
    dosage: '20 mg',
    description: 'ยาลดการสร้างกรดในทางอาหาร',
    img: 'https://135487417.cdn6.editmysite.com/uploads/1/3/5/4/135487417/s300591935886541537_p696_i1_w2326.jpeg',
  },
  {
    name: 'Metformin',
    drugGroup: 'antidiabetic',
    dosage: '500 mg',
    description: 'ใช้สำหรับรักษาเบาหวาน',
    img: 'https://www.scharoen.com/wp-content/uploads/2022/07/Metformin-500-mg-100X10.jpg',
  },
  {
    name: 'Simvastatin',
    drugGroup: 'statin',
    dosage: '20 mg',
    description: 'ลดระดับคอเลสเตอรอล',
    img: 'https://medtide.com/wp-content/uploads/2020/09/Simvastatin-Bestatin-20-mg-100-tablets.png',
  },
  {
    name: 'Lisinopril',
    drugGroup: 'ACE inhibitor',
    dosage: '10 mg',
    description: 'ลดความดันโลหิต',
    img: 'https://medtide.com/wp-content/uploads/2021/08/Lisinopril-Lispril-5-mg.png',
  },
  {
    name: 'Albuterol',
    drugGroup: 'bronchodilator',
    dosage: '100 mcg',
    description: 'ใช้สำหรับการบรรเทาอาการหายใจ',
    img: 'https://www.mountainside-medical.com/cdn/shop/products/Albuterol-inhalation-Solution-3ml.jpg?v=1600347713',
  },
  {
    name: 'Hydrochlorothiazide',
    drugGroup: 'diuretic',
    dosage: '25 mg',
    description: 'ลดน้ำ ลดความดันโลหิต',
    img: 'https://s.turbifycdn.com/aah/yhst-135855760451349/hydrochlorothiazide-25mg-per-tablet-67.jpg',
  },
  {
    name: 'prednisone',
    drugGroup: 'corticosteroid',
    dosage: '5 mg',
    description: 'ใช้สำหรับการลดอักเสบ',
    img: 'https://s.turbifycdn.com/aah/yhst-135855760451349/prednisone-20-mg-per-tablet-34.jpg',
  },
  {
    name: 'Cetirizine',
    drugGroup: 'antihistamine',
    dosage: '10 mg',
    description: 'ยาแก้พ้อากาศ',
    img: 'https://www.siamhealth.net/public_html/images/med/%E0%B8%A2%E0%B8%B2%E0%B9%81%E0%B8%81%E0%B9%89%E0%B9%81%E0%B8%9E%E0%B9%89%E0%B8%AD%E0%B8%B2%E0%B8%81%E0%B8%B2%E0%B8%A8.webp',
  },
  {
    name: 'warfarin',
    drugGroup: 'anticoagulant',
    dosage: '5 mg',
    description: 'ลดการเกิดลิ่มเลือด',
    img: 'https://vinmec-prod.s3.amazonaws.com/images/20210205_124053_832225_thuoc-Warfarin.max-1800x1800.png',
  },
  {
    name: 'Diazepam',
    drugGroup: 'anxiolytic',
    dosage: '5 mg',
    description: 'ใช้สำหรับการสงบประสาท',
    img: 'https://5.imimg.com/data5/SELLER/Default/2023/2/XP/KO/EM/38282849/valium-diazepam-packaging-type-boxdosage10-mg.JPG',
  },
  {
    name: 'Levothyroxine',
    drugGroup: 'thyroid hormone',
    dosage: '50 mcg',
    description: 'ใช้สำหรับการรักษาปัญหาของต่อมไทรอยด์',
    img: 'https://www.marham.pk/healthblog/wp-content/uploads/2023/04/English-Blogs-16.png',
  },
  {
    name: 'Ciprofloxacin',
    drugGroup: 'antibiotic',
    dosage: '500 mg',
    description: 'ใช้สำหรับการต่อต้านเชื้อโรค',
    img: 'https://fidson.com/wp-content/uploads/2022/09/Ciprofloxacin-500-768x768.png',
  },
  {
    name: 'Metoprolol',
    drugGroup: 'beta blocker',
    dosage: '50 mg',
    description: 'ลดความเร็วของการเต้นหัวใจ',
    img: 'https://k2pharmacy.ph/cdn/shop/products/MetoprololTartrate50mgTablet1.jpg?v=1671081764',
  },
  {
    name: 'Paracetamol',
    drugGroup: 'NSAIDs',
    dosage: '500 mg',
    description: 'แก้ปวด ลดไข้',
    img: 'https://assets.sainsburys-groceries.co.uk/gol/8075006/1/640x640.jpg',
  },
  {
    name: 'Penicillin',
    drugGroup: 'antibiotic',
    dosage: '250 mg',
    description: 'ใช้สำหรับการต่อต้านเชื้อโรค',
    img: 'https://5.imimg.com/data5/SELLER/Default/2023/5/311848034/ZD/QZ/SY/160984895/penicillin-g.jpeg',
  },
  {
    name: 'Clarithromycin',
    drugGroup: 'antibiotic',
    dosage: '500 mg',
    description: 'ใช้สำหรับการต่อต้านเชื้อโรค',
    img: 'https://www.grxstatic.com/d4fuqqd5l3dbz/products/Package_27179.JPG',
  },
  {
    name: 'Diphenhydramine',
    drugGroup: 'antihistamine',
    dosage: '25 mg',
    description: 'ใช้สำหรับแก้อาการแพ้',
    img: 'https://www.benadryl.com.ph/sites/benadryl_ph/files/styles/product_image/public/product-images/ah_side.png',
  },
  {
    name: 'Ranitidine',
    drugGroup: 'H2 blocker',
    dosage: '150 mg',
    description: 'ลดการผลิตกรดในกระเพาะอาหาร',
    img: 'https://static.theprint.in/wp-content/uploads/2019/10/ranitidine.jpg',
  },
  {
    name: 'Propranolol',
    drugGroup: 'beta blocker',
    dosage: '40 mg',
    description: 'ลดความเร็วของการเต้นหัวใจ',
    img: 'https://cth.co.th/wp-content/uploads/2021/09/propranolol-2.jpg',
  },
  {
    name: 'Naproxen',
    drugGroup: 'NSAIDs',
    dosage: '220 mg',
    description: 'แก้ปวด ลดอักเสบ',
    img: 'https://m.media-amazon.com/images/I/71TDu1rY2WL._AC_SX679_.jpg',
  },
  {
    name: 'Cimetidine',
    drugGroup: 'H2 blocker',
    dosage: '200 mg',
    description: 'ลดการผลิตกรดในกระเพาะอาหาร',
    img: 'https://i5.walmartimages.com/seo/Equate-Cimetidine-Tablets-200-mg-Acid-Reducer-120-Ct_bdff878b-e027-4c70-be02-3334983a0e41.f5f695c981ac3f3b3c7814bddcd15e8d.jpeg',
  },
  {
    name: 'Atenolol',
    drugGroup: 'beta blocker',
    dosage: '50 mg',
    description: 'รักษาความดันโลหิตสูงและอาการเจ็บหน้าอก',
    img: 'https://5.imimg.com/data5/SELLER/Default/2022/7/HZ/FZ/TL/38378827/atenolol-50-mg-hydrochlorothiazide-12-5-mg.jpg',
  },
  {
    name: 'Prednisolone',
    drugGroup: 'corticosteroid',
    dosage: '5 mg',
    description: 'ใช้สำหรับการลดอักเสบ',
    img: 'https://osi.co.th/wp-content/uploads/2022/11/PREDNISOLONE.jpg',
  },
];
